### ISSUE TITLE
missing json file:  'mot/annotations/train_half.json'

### ISSUE THREAD

**Issue by Kewenjing1020** [PeizeSun/TransTrack#19]
Hi, I tried to run eval on mot dataset `sh track_exps/mot_val.sh`. It reports an error:
```
loading annotations into memory...
Traceback (most recent call last):
  File "main_track.py", line 366, in <module>
    main(args)
  File "main_track.py", line 174, in main
    dataset_train = build_dataset(image_set=args.track_train_split, args=args)
  File "/proj/xcdhdstaff1/wenjingk/transformer/TransTrack-main/datasets/__init__.py", line 23, in build_dataset
    return build_mot(image_set, args)
  File "/proj/xcdhdstaff1/wenjingk/transformer/TransTrack-main/datasets/mot.py", line 242, in build
    cache_mode=args.cache_mode, local_rank=get_local_rank(), local_size=get_local_size())
  File "/proj/xcdhdstaff1/wenjingk/transformer/TransTrack-main/datasets/mot.py", line 25, in __init__
    cache_mode=cache_mode, local_rank=local_rank, local_size=local_size)
  File "/proj/xcdhdstaff1/wenjingk/transformer/TransTrack-main/datasets/torchvision_datasets/coco.py", line 93, in __init__
    self.coco = COCO(annFile)
  File "/home/wenjingk/.local/lib/python3.6/site-packages/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'mot/annotations/train_half.json'
```
It seems this json file is not publicly provided. Could you help with this?

**Comment by PeizeSun** [comment]
Hi~
You should prepare mot annotations first as the steps in README.
`python track_tools/convert_mot_to_coco.py
`

**Comment by Kewenjing1020** [comment]
Thank you for your reply. The problem is solved now.
