### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 3 (char 4)

### ISSUE THREAD

**Issue by GuoHuaqiang** [PeizeSun/TransTrack#68]
Hi, thank you for your great work on TransTrack. It is really awesome. I successfully reproduce the model based on the steps you provided. Now I try to apply the model on my dataset and then try to train the model, but there are some problems. I used CVAT to label the video datasets and export them in COCO format (.json file). I divide all the datasets into two files as train.json and test.json respectively in annotation file. And then I try to train the model. But the errors appear like “json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 3 (char 4)”(Figure1). 
```
Not using distributed mode
git:
  sha: 7c3458a85a981b7c9a935c264133b477928f4648, status: has uncommited changes, branch: main

Namespace(aux_loss=True, backbone='resnet50', batch_size=2, bbox_loss_coef=5, cache_mode=False, checkpoint_dec_ffn=False, checkpoint_enc_ffn=False, clip_max_norm=0.1, cls_loss_coef=2, coco_panoptic_path=None, coco_path='grade_cross', dataset_file='grade_cross', dec_layers=6, dec_n_points=4, det_val=False, device='cuda', dice_loss_coef=1, dilation=False, dim_feedforward=1024, dist_video=False, distributed=False, dropout=0.1, enc_layers=6, enc_n_points=4, epochs=150, eval=False, focal_alpha=0.25, fp16=False, frozen_weights=None, giou_loss_coef=2, hidden_dim=256, id_loss_coef=1, lr=0.0002, lr_backbone=2e-05, lr_backbone_names=['backbone.0'], lr_drop=100, lr_drop_epochs=None, lr_linear_proj_mult=0.1, lr_linear_proj_names=['reference_points', 'sampling_offsets'], mask_loss_coef=1, masks=False, nheads=8, num_feature_levels=4, num_ids=360, num_queries=500, num_workers=2, output_dir='./output_GradeCross', position_embedding='sine', position_embedding_scale=6.283185307179586, reid_dim=128, reid_shared=False, remove_difficult=False, resume='crowdhuman_final.pth', seed=42, set_cost_bbox=5, set_cost_class=2, set_cost_giou=2, sgd=False, start_epoch=0, start_id=1, track_eval_split='val', track_thresh=0.4, track_train_split='train', two_stage=False, weight_decay=0.0001, with_box_refine=True)
number of params: 46874770
loading annotations into memory...
Traceback (most recent call last):
  File "main_track.py", line 392, in <module>
    main(args)
  File "main_track.py", line 186, in main
    dataset_train = build_dataset(image_set=args.track_train_split, args=args)
  File "/home/huaqiang/TransTrack/datasets/__init__.py", line 31, in build_dataset
    return build_GradeCross(image_set, args)
  File "/home/huaqiang/TransTrack/datasets/grade_cross.py", line 170, in build
    cache_mode=args.cache_mode, local_rank=get_local_rank(), local_size=get_local_size())
  File "/home/huaqiang/TransTrack/datasets/grade_cross.py", line 31, in __init__
    cache_mode=cache_mode, local_rank=local_rank, local_size=local_size)
  File "/home/huaqiang/TransTrack/datasets/torchvision_datasets/coco.py", line 93, in __init__
    self.coco = COCO(annFile)
  File "/home/huaqiang/anaconda3/envs/trans/lib/python3.7/site-packages/pycocotools/coco.py", line 82, in __init__
    dataset = json.load(f)
  File "/home/huaqiang/anaconda3/envs/trans/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/huaqiang/anaconda3/envs/trans/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/huaqiang/anaconda3/envs/trans/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/huaqiang/anaconda3/envs/trans/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 3 (char 4)
```
I think it is because of the dataset format. I compared my own dataset json file with your original train.json file in annotation and I found it is very different. What do you think of this problem? How can I label data to have the same data format with annotations of CrowdHuman and MOT17 datasets?

**Comment by PeizeSun** [comment]
It seems that your json format is not correct. Maybe you could refer our [code](https://github.com/PeizeSun/TransTrack/blob/main/track_tools/convert_mot_to_coco.py) to reformat your json file.

**Comment by jer1ry** [comment]
Hi
I know you successfully reproduce the model, can you tell me how? I want to reproduce it, thank you very much.
@GuoHuaqiang
